version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadbOT
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: otdb
      MYSQL_USER: symfony
      MYSQL_PASSWORD: OT
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pmaOT
    environment:
      PMA_HOST: mariadb
      PMA_USER: symfony
      PMA_PASSWORD: OT
      UPLOAD_LIMIT: 64M
    ports:
      - "8088:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
